name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GTest
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          cd /usr/src/googletest/googletest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project and tests
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  run_prog:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Run main program
        run: |
          cd build
          if [ -f ../graph.txt ]; then
            cp ../graph.txt .
          fi
          ./graph_program

  run_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
        
      - name: Run tests
        run: |
          cd build
          ctest --verbose
